package com.example.libraryapp

import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.widget.Button
import android.widget.ImageView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class BookInfoActivity : AppCompatActivity() {

    private val descriptions = mapOf(
        "book_0001" to "Red, White & Royal Blue is an LGBT romance novel by American author Casey McQuiston, originally published on May 14, 2019, by St Martin's Griffin. It centres on the character of Alex Claremont-Diaz, a first son of the United States, and his romantic relationship with Prince Henry, a British prince.[2] Upon release, the novel received positive reviews with praise given to the representation of a queer male relationship. A film adaptation was released on August 11, 2023.",
        "book_0002" to "Jane Eyre /ɛər/ (originally published as Jane Eyre: An Autobiography) is a novel by English writer Charlotte Brontë, published under the pen name Currer Bell, on 16 October 1847, by Smith, Elder & Co. of London. The first American edition was published the following year by Harper & Brothers of New York. Jane Eyre is a Bildungsroman which follows the experiences of its eponymous heroine, including her growth to adulthood and her love for Mr. Rochester, the brooding master of Thornfield Hall. The novel revolutionised prose fiction by being the first to focus on its protagonist's moral and spiritual development through an intimate first-person narrative, where actions and events are coloured by a psychological intensity. " +
                "Charlotte Brontë has been called the first historian of the private consciousness, and the literary ancestor of writers like Proust and Joyce. The book contains elements of social criticism with a strong sense of Christian morality at its core, and it is considered by many to be ahead of its time because of Jane's individualistic character and how the novel approaches the topics of class, sexuality, religion, and feminism. It, along with Jane Austen's Pride and Prejudice, is one of the most famous romance novels of all time.",
        "book_0003" to "For all the trappings of success—his multinational businesses, his vast wealth, his loving family—Grey is a man tormented by demons and consumed by the need to control. When the couple embarks on a daring, passionately physical affair, Ana discovers Christian Grey's secrets and explores her own dark desires.",
        "book_0004" to "Eleanor and Park by Rainbow Rowell is a poignant young adult novel that explores themes of love, identity, and resilience. Set in the 1980s, it tells the story of Eleanor, a quirky and artistic girl with a troubled family life, and Park, a half-Korean boy who feels like an outsider despite his efforts to blend in. As they bond over comic books and mixtapes on their daily bus rides, their relationship evolves from cautious friendship to a deep and tender romance. However, their love faces challenges from Eleanor's difficult home situation and the prejudices they encounter at school. Rowell's narrative captures the awkward beauty of first love amidst adversity, offering a touching portrayal of two young people finding solace and strength in each other's differences.",
        "book_0005" to "The Proposal by Jasmine Guillory is a contemporary romance novel that blends humor, modern dating dilemmas, and heartfelt emotions. When Nikole Paterson's casual relationship with her boyfriend ends abruptly at a Dodgers game with a very public proposal (that she rejects), she finds unexpected comfort in Carlos Ibarra, a kind stranger and doctor in the stands. As they navigate their growing attraction and the complexities of their personal lives, Nikole, a freelance writer, and Carlos, a pediatrician, discover common ground beyond their initial connection. Guillory weaves a tale of second chances and self-discovery, exploring themes of independence, friendship, and the unpredictable nature of love in the digital age. The Proposal offers a refreshing take on romance, emphasizing empowerment and authenticity in relationships.",
        "book_0006" to "And Then I Met You by Erica Lee is a heartfelt contemporary romance novel that delves into the transformative power of unexpected connections. The story follows Emily Li, a career-driven lawyer in New York City, whose meticulously planned life takes an unexpected turn when she meets Jason Chow, a charming and free-spirited artist. Their chance encounter sparks a whirlwind romance that challenges Emily's carefully constructed barriers and opens her heart to new possibilities. As their relationship deepens, they navigate cultural differences, personal ambitions, and the uncertainties of falling in love. Lee's narrative is a celebration of serendipity and the profound impact of love on personal growth, blending moments of humor, tenderness, and self-discovery. And Then I Met You is a compelling tale of romance and resilience, reminding us that sometimes the best things in life happen when we least expect them.",
        "book_0007" to "Meg Thurgood, former society girl, took the blame for her friend and paid a steep price. Now all she wants is solitude and a chance to rebuild her life. She thinks she's found that in an isolated house she rents from a mysterious stranger. Simon McAlter has hidden in his house on the coast of Maine since a fire left him scarred. A successful landscape architect who conducts his business and teaches his classes remotely, he's lost his inspiration and is trying to pretend he's not lonely. Simon's new neighbor is more than he bargained for. When he learns Meg's secret, will he retreat into the shadows or will he learn to see past the surface and trust in Meg's love?",
        "book_0008" to "In The Finish Line, the seventh and final installment of Erica Lee's beloved The Six Pack series, the journey of friendship, love, and personal growth reaches its dramatic conclusion. The story follows the tight-knit group of friends as they navigate the final challenges and triumphs that life throws their way. With each member of the group facing their own pivotal moments, the bonds between them are tested like never before. This book delves deep into themes of perseverance, loyalty, and the power of enduring friendships. Erica Lee masterfully weaves together each character's storyline, ensuring a satisfying and emotional end to the series. Readers will find themselves laughing, crying, and cheering for the characters they've come to know and love. The Finish Line is a poignant and uplifting conclusion that celebrates the strength of unity and the importance of finishing strong, no matter the obstacles.",
        "book_0009" to "Summer, 1993. In the aftermath of her mother's suicide attempt, 16-year-old Prue must spend the summer holidays on a remote island in the Shetlands with her favourite Aunt Ruth and Uncle Archie, a man she's barely met since her aunt married him. Prue hopes to re-establish the relationship, and that her aunt might help her understand some of the parts of the past she has been forbidden to discuss by her mother – including the identity of her father. Prue soon finds out her uncle was the only suspect in the disappearance of a local girl some twenty years ago. As she grows closer to him, she learns there are different views on how the beguiling Evelyn O'Hara disappeared, but is he innocent?",
        "book_0010" to "Dryad's Blade by Kater Cheek is a fantasy novel that immerses readers in a world where magic, adventure, and ancient mysteries converge. The story follows Tiel, a young woman who discovers she has the ability to communicate with trees, a rare and powerful gift known as dryad magic. When a series of mysterious and dangerous events threaten her homeland, Tiel must harness her newfound abilities and embark on a quest to uncover the truth behind these dark forces.Cheek's narrative weaves together elements of magic, mythology, and suspense, as Tiel navigates treacherous landscapes and encounters mythical creatures. Along the way, she forms alliances with unlikely allies and confronts her own inner struggles, making choices that will determine the fate of her world. Dryad's Blade is a gripping tale of courage, destiny, and the enduring bond between nature and humanity, appealing to fans of epic fantasy and immersive storytelling.",
        "book_0011" to "The Girl on the Run by Gregg Olsen is a suspenseful thriller that follows the story of a young woman named Nicole Foster. She finds herself on the run after witnessing a brutal crime committed by her boyfriend's father, a powerful and dangerous man. As she tries to evade capture and uncover the truth behind the crime, Nicole must navigate through a web of deceit and danger, unsure whom she can trust. Olsen crafts a gripping narrative filled with twists and turns, keeping readers on the edge of their seats as Nicole races against time to clear her name and survive. The Girl on the Run is a compelling tale of suspense and survival, exploring themes of trust, betrayal, and the lengths one will go to protect themselves.",
        "book_0012" to "Such Fine Boys is a poignant exploration of memory and identity set against the backdrop of post-World War II Paris. The novel follows a middle-aged man reflecting on his youth in the 1960s, a period marked by the city's vibrant bohemian culture and the lingering shadows of wartime experiences. The protagonist recalls his close-knit group of friends, navigating the complexities of relationships and aspirations amidst the city's cafes, streets, and hidden corners. " +
                "As he revisits these memories, the narrative intertwines moments of introspection with vivid snapshots of Parisian life, capturing both the allure and disillusionment of youthful dreams. Modiano's prose is introspective and evocative, drawing readers into a world where past and present converge, exploring themes of nostalgia, loss, and the search for meaning in a rapidly changing world. " +
                "Such Fine Boys is a testament to Modiano's mastery in portraying the intricacies of human experience and the enduring power of memory.",
        "book_0013" to "The Lifeline by Libby Page is a novel that captures the transformative power of community and friendship. Set in London, it tells the story of Rosemary, an elderly woman who has swum at the local lido (an outdoor swimming pool) for decades, finding solace and joy in its waters. When the lido is threatened with closure, Kate, a young journalist, discovers the story and forms an unlikely friendship with Rosemary. Together, they embark on a campaign to save the lido, rallying their community and finding strength in their shared mission." +
                "       Page's narrative explores themes of connection, the importance of local spaces, and the impact of change on individuals and communities. It is a heartwarming tale that celebrates the resilience of the human spirit and the power of coming together in times of need.",
        "book_0014" to "Walt Disney's Goofy Movie Star is a children's book that celebrates the beloved Disney character Goofy's adventures as he steps into the spotlight. In this story, Goofy finds himself unexpectedly becoming a movie star, navigating the glitz and glamour of Hollywood while staying true to his goofy and lovable personality. Along the way, Goofy encounters challenges, comedic mishaps, and heartwarming moments that highlight the importance of friendship, perseverance, and staying true to oneself. The book captures Goofy's signature charm and humor, making it an enjoyable read for young Disney fans and anyone who appreciates classic cartoon characters brought to life through storytelling.",
        "book_0015" to "Across Europe, on what history will call D-Day, five unforgettable women from all walks of life strive to survive the most terrifying night of their lives." +
                "Told in alternating viewpoints, this unforgettable debut is perfect for fans of Kate Quinn and Pam Jenoff." +
                " June 6, 1944. Allied forces hit the beaches of Nazi-occupied France. Among the countless lives shattered are those of five spirited women with starkly different lives. As the war reaches its tipping point, each of the women fight for the survival of themselves, their countries, and their way of life during one of the most pivotal days in history." +
                "American expatriate Mildred, better known as Axis Sally, has a thriving career as a Nazi radio propagandist, but her conscience haunts her. Meanwhile, across the English Channel, young medical volunteer Theda is pushed to her limit as shiploads of casualties dock in Portsmouth. Closer to the front, intrepid Flora aids the French resistance, while she seeks out her vanished parents. Iron-willed Emilia has climbed the Gestapo ranks, but she is now bent on betraying them. Finally, dignified Adelaide’s faith is shaken when she is forced to quarter German soldiers.",
        "book_0016" to "Suzume is a Japanese light novel that takes readers on a journey through the life of its protagonist, Suzume. Set in a captivating world where magic, adventure, and mystery intertwine, Suzume discovers she possesses a unique ability or encounters a significant event that changes her life forever. As she navigates through challenges and explores the depths of her newfound powers, Suzume forms bonds with diverse characters who shape her journey. Themes of courage, friendship, and personal growth resonate throughout the narrative, offering readers a rich tapestry of emotions and experiences. The novel combines elements of fantasy and coming-of-age storytelling, immersing readers in vivid landscapes and imaginative scenarios. With its compelling plot twists and heartfelt moments, Suzume captivates audiences with its blend of whimsy, intrigue, and the timeless quest for identity and purpose.",
        "book_0017" to "Eminence in Shadow (Kage no Jitsuryokusha ni Naritakute!) is a Japanese light novel series written by Daisuke Aizawa and illustrated by Touzai. Here's a description" +
                "       Eminence in Shadow follows the story of Cid Kagenou, a high school student who is obsessed with the idea of becoming a protagonist in a secret organization's mission. Despite lacking any real combat skills or magical abilities, Cid decides to form his own shadow organization with his friends and allies. Using his knowledge of fictional tropes and strategies gleaned from manga, anime, and games, Cid sets out to create his ideal role as a mysterious and powerful figure working behind the scenes." +
                "       As Cid navigates through various challenges and encounters formidable foes, the series explores themes of ambition, identity, and the blurred lines between fantasy and reality in a world filled with magic and intrigue. Eminence in Shadow is known for its humor, clever references to pop culture, and the protagonist's unconventional approach to achieving greatness.",
        "book_0018" to "In her past life, Asura was a soldier of fortune who lived for the battle above all else. So when she reincarnates into a world with magic, she gladly takes up the mercenary’s path for a second time. Drawing upon her battle-hardened experience, she forms the mercenary group Moon Blossom and pioneers the concept of the soldier-mage: magic users who also fight with the skills and training of military soldiers. Roaming the battlefields of this new world, Moon Blossom—led by Asura and her unrivaled schemes, ruthlessness, and tactical ingenuity—earns a fearsome reputation. Thus the curtain rises on the dark fantasy epic of a young girl who is spoken of in fearful whispers as “The Silver Demon”!",
        "book_0019" to "Mushoku Tensei: Jobless Reincarnation is a Japanese light novel series written by Rifujin na Magonote and illustrated by Shirotaka. Here's an overview:" +
                "       Mushoku Tensei follows the story of a 34-year-old Japanese NEET (Not in Education, Employment, or Training) named Rudeus Greyrat, who dies in a traffic accident and is reincarnated into a magical world as an infant. Retaining his memories and intellect from his previous life, Rudeus resolves to live a fulfilling life this time around, armed with newfound magical abilities in a world of swords and sorcery." +
                "       As he grows up under the care of his loving parents in a world filled with fantastical creatures and powerful magic, Rudeus embarks on a journey of self-discovery, redemption, and personal growth. He trains diligently to become a powerful mage while forming bonds with various characters who shape his destiny. The series explores themes of second chances, adventure, and the complexities of life in a fantasy realm." +
                "       Mushoku Tensei has been praised for its detailed world-building, character development, and exploration of mature themes. It has also been adapted into manga and anime, further expanding its popularity among fans of isekai (reincarnation in another world) and fantasy genres.",
        "book_0020" to "Jujutsu Kaisen by Gege Akutami is a popular Japanese manga series that has also been adapted into an anime. Here's a description:" +
                "       Jujutsu Kaisen follows the story of Yuji Itadori, a high school student with remarkable physical abilities. When Yuji encounters a cursed object containing a powerful curse, he unwittingly becomes involved in the world of jujutsu sorcerers, who battle curses and supernatural threats. To protect his friends and the world from the dangers unleashed by curses, Yuji decides to join Tokyo Metropolitan Magic Technical College (Jujutsu High) and train as a jujutsu sorcerer. Alongside his classmates, including the enigmatic and skilled sorcerer Megumi Fushiguro and the cheerful but powerful Nobara Kugisaki, Yuji embarks on dangerous missions to exorcise curses and uncover the mysteries surrounding them." +
                "       Jujutsu Kaisen is known for its dynamic action scenes, intricate world-building, and complex characters, offering readers and viewers a thrilling and immersive experience into the realm of supernatural battles and moral dilemmas.",
        "book_0021" to "Attack on Titan (Shingeki no Kyojin) is a highly acclaimed Japanese manga series written and illustrated by Hajime Isayama. Here's an overview:" +
                "       Attack on Titan is set in a world where humanity resides within enormous walled cities to protect themselves from Titans, gigantic humanoid creatures who devour humans seemingly without reason. The story begins with the sudden appearance of a colossal Titan that breaches the outer wall of one of these cities, leading to chaos and the loss of many lives. The main protagonist, Eren Yeager, witnesses the destruction and vows to eradicate all Titans after his mother is killed in the attack." +
                "       As the series progresses, Eren, along with his adopted sister Mikasa Ackerman and friend Armin Arlert, joins the military to fight against Titans using specially designed equipment known as Vertical Maneuvering Equipment (3D Maneuver Gear). The narrative delves into complex themes such as freedom, survival, and the consequences of war, while uncovering mysteries surrounding the Titans' origins and the history of humanity itself." +
                "       Attack on Titan has gained widespread popularity for its intense action sequences, intricate plot twists, and morally ambiguous characters. It has also been adapted into an anime series that further expands upon the manga's storyline.",
        "book_0022" to "Itachi’s Story, Vol. 1: Daylight delves into the complex and enigmatic life of one of the most beloved characters in the Naruto universe, Itachi Uchiha. Born into the prestigious Uchiha clan, Itachi is a prodigious ninja, whose skills and intellect set him apart from his peers at a very young age. However, his extraordinary talents come with immense burdens and responsibilities that shape his destiny in profound ways." +
                        "From the tender age of four, Itachi witnesses the horrors of the ninja world, leaving an indelible mark on his psyche. His deep sense of justice and yearning for peace lead him to question the violent traditions and political machinations that underpin ninja society. Itachi's story is one of sacrifice, loyalty, and the moral dilemmas that come with the quest for a utopian vision of the world." +
                        "As he grows, Itachi becomes a double agent, joining the notorious Akatsuki organization to protect his village from within. The book explores his internal conflicts as he balances his duty to his clan, his love for his younger brother Sasuke, and his covert mission to prevent a coup that could plunge the village into chaos." +
                        "Kishimoto masterfully weaves a narrative that captures the tragic heroism of Itachi. Through rich character development and intricate plotlines, readers gain a deeper understanding of Itachi's motivations and the heavy toll of his choices. The novel also sheds light on his relationships, particularly with his family and close friend Shisui, whose own fate profoundly influences Itachi's path.",
        "book_0023" to "Crimson Lake by Candace Fox is a gripping mystery novel that delves into the lives of two outcasts drawn together by their shared need for redemption and truth. Set in the eerie and atmospheric town of Crimson Lake in Queensland, Australia, the novel introduces us to Ted Conkaffey, a former police detective whose life has been shattered by a false accusation of child abduction and rape. Despite the charges being dropped, the stain on his reputation has led him to retreat to the remote town, seeking solitude and anonymity." +
                "Upon arrival, Ted is introduced to Amanda Pharrell, a quirky and enigmatic private investigator with a dark past of her own. Amanda has served time for murder and now works on cases that the police have written off as unsolvable. Her eccentric personality and unorthodox methods make her an intriguing partner for Ted, who reluctantly joins forces with her." +
                "The pair is hired to investigate the disappearance of a local author, Jake Scully, whose wife fears the worst. As they delve deeper into the case, they uncover a web of secrets, lies, and hidden agendas that shake the very foundation of the seemingly quiet town. The investigation forces Ted and Amanda to confront their own demons while navigating the murky waters of small-town politics and the dark side of human nature." +
                "Fox masterfully builds tension and suspense, using the lush and treacherous Australian landscape as a backdrop that almost becomes a character in its own right. The swamps, dense forests, and oppressive heat add an element of danger and unpredictability to the narrative. Her writing is vivid and evocative, drawing readers into the world of Crimson Lake with its unique blend of beauty and menace.",
        "book_0024" to "Murder On The Orient Express by Agatha Christie is a classic detective novel that epitomizes the golden age of mystery fiction. Set aboard the luxurious and iconic Orient Express train, the story follows renowned detective Hercule Poirot as he embarks on a journey from Istanbul to Calais. What begins as a lavish and uneventful trip quickly turns into a thrilling investigation when a wealthy American passenger, Samuel Ratchett, is found murdered in his compartment." +
                "Poirot, known for his keen powers of observation and meticulous attention to detail, is thrust into a complex web of clues and suspects. With the train halted by a snowdrift, he must unravel the truth behind Ratchett’s death before the murderer strikes again or escapes into the night. The suspects aboard the train are a diverse cast of characters, each with their own motives and secrets, adding layers of intrigue to the investigation." +
                "Christie’s masterful storytelling unfolds through a series of interviews, revelations, and clever deductions as Poirot painstakingly pieces together the puzzle. The novel not only showcases Poirot’s brilliance as a detective but also explores themes of justice, morality, and the consequences of past actions. As the truth is uncovered, readers are drawn deeper into a labyrinth of deceit and deception, culminating in a shocking and unforgettable conclusion.",
        "book_0025" to "Destination Unknown by Agatha Christie takes readers on a gripping journey into the world of espionage and intrigue. The novel follows the story of Hilary Craven, a disillusioned woman who is devastated by the recent death of her child and the collapse of her marriage. Faced with overwhelming grief and despair, she contemplates ending her own life but instead decides to embark on a dangerous and clandestine mission that offers a glimmer of purpose." +
                "Recruited by a shadowy organization, Hilary is thrust into a world of espionage where nothing is as it seems. Her assignment takes her across Europe, from London to Morocco, as she infiltrates a sinister conspiracy that threatens global stability. Along the way, she encounters a diverse cast of characters, each with their own agendas and secrets, as she navigates a maze of deception and danger." +
                "Christie’s trademark suspense and meticulous plotting are on full display as Hilary races against time to uncover the truth behind the mysterious organization and its nefarious plans. The novel explores themes of identity, resilience, and the moral ambiguity of espionage, challenging readers to question where loyalties truly lie in a world of shifting allegiances." +
                "As Hilary delves deeper into the conspiracy, she must confront her own fears and vulnerabilities while grappling with the ethical dilemmas posed by her mission. Her journey is a testament to the human spirit’s capacity for survival and transformation in the face of adversity.",
        "book_0026" to "The Canterville Ghost by Oscar Wilde is a charming and humorous ghost story that deftly blends satire with elements of the supernatural. Set in rural England, the novella follows the Otis family, an American clan who purchases Canterville Chase, an ancient English manor rumored to be haunted by the ghost of Sir Simon de Canterville." +
                "The story unfolds as the brash and pragmatic Otis family moves into the mansion, completely unfazed by the ghostly warnings and paranormal phenomena that greet them. Sir Simon, the ghost, is accustomed to terrifying and driving away previous occupants, but the Otis family’s skepticism and modern sensibilities prove to be formidable adversaries. " +
                "Wilde uses wit and irony to critique both British aristocratic traditions and American pragmatism through the interactions between the ghost and the Otis family. Despite Sir Simon’s best efforts to scare them away, the Otis children respond with practical jokes and inventions designed to thwart the ghost’s haunting attempts. This clash of old-world spookiness and new-world pragmatism forms the heart of the novella’s humor and charm." +
                "As the story progresses, Wilde explores themes of forgiveness, redemption, and the transformative power of love. Through his interactions with Virginia, the Otis daughter, Sir Simon begins to confront the consequences of his past deeds and seeks a path to peace and salvation.",
        "book_0027" to "The Girl Before Me by Laura Wolfe is a psychological thriller that delves into the complexities of identity, obsession, and the dark secrets hidden within a seemingly perfect life. The novel centers around Clara Lawson, a young woman who finds herself entangled in a web of deceit and danger after assuming the identity of a missing girl, Emory." +
                "Clara, a skilled con artist with a troubled past, sees Emory’s disappearance as an opportunity for a fresh start. She takes over Emory’s life, including her job, home, and relationships, seamlessly integrating herself into the missing girl’s world. However, as Clara delves deeper into Emory’s life, she uncovers disturbing truths and realizes that she may not be the only one hiding secrets." +
                "Wolfe skillfully weaves a narrative that alternates between Clara’s present-day experiences and Emory’s past, gradually revealing the events that led to Emory’s disappearance. As Clara navigates the complexities of her dual identity, she becomes increasingly paranoid and distrustful of those around her, unsure of who she can truly rely on." +
                "The novel explores themes of identity theft, manipulation, and the blurred lines between truth and deception. Clara’s journey is a gripping exploration of how far someone will go to escape their past and the consequences of living a lie. As she races against time to uncover the truth about Emory’s disappearance, Clara must confront her own demons and face the repercussions of her actions.",
        "book_0028" to "The Killing Room by John Manning is a chilling psychological thriller that plunges readers into a terrifying game of cat and mouse. The novel centers around Dr. Peter Gram, a renowned psychiatrist who specializes in treating patients with severe phobias. When Peter’s own wife falls victim to a brutal murder, he becomes obsessed with finding her killer and seeking justice." +
                "As Peter delves deeper into the investigation, he uncovers a series of horrifying connections between his wife’s death and a string of unsolved murders. Each victim suffered from extreme phobias, and their deaths seem to be intricately linked to their deepest fears. Peter soon realizes that he is being targeted by a ruthless killer who is playing a deadly game of psychological manipulation." +
                "Manning masterfully builds tension and suspense as Peter races against time to uncover the truth before he becomes the next victim. The novel explores themes of fear, obsession, and the lengths people will go to in order to confront their darkest demons. As Peter confronts his own fears and vulnerabilities, he must navigate a labyrinth of secrets and betrayal to uncover the identity of the killer." +
                "The psychological depth of The Killing Room is enhanced by Manning’s skillful characterization and intricate plot twists. Each revelation adds layers to the mystery, keeping readers guessing until the final, heart-pounding conclusion. The novel’s atmospheric setting and relentless pacing create a sense of unease and paranoia, drawing readers deeper into Peter’s desperate quest for answers.",
        "book_0029" to "Appointment With Death by Agatha Christie is a classic murder mystery that showcases the unparalleled deductive skills of Hercule Poirot. Set against the backdrop of an exotic journey through the Middle East, the novel follows Poirot as he investigates the suspicious death of Mrs. Boynton, a tyrannical matriarch who holds her family in a grip of fear and manipulation." +
                "The Boynton family, consisting of stepchildren and their spouses, are on a tour of archaeological sites when Mrs. Boynton suddenly dies under mysterious circumstances. Initially dismissed as natural causes, Poirot suspects foul play and begins unraveling the complex dynamics and hidden resentments within the family." +
                "Christie’s meticulous plotting and keen observation bring each character to life, revealing their motives and secrets as Poirot conducts his investigation. The novel explores themes of power, control, and the psychological effects of manipulation, as Poirot uncovers layers of deception and betrayal among the suspects." +
                "As Poirot pieces together the puzzle, he navigates a labyrinth of clues and red herrings, ultimately leading to a surprising and satisfying conclusion. Christie’s ability to maintain suspense and intrigue until the final reveal has made Appointment With Death a beloved classic among mystery enthusiasts." +
                "Through Poirot’s methodical approach and sharp wit, Christie explores the complexities of human nature and the moral dilemmas that arise when confronted with guilt and justice. Appointment With Death is not just a mystery novel; it is a compelling exploration of the darker aspects of the human psyche and the consequences of unchecked power.",
        "book_0030" to "Misery by Stephen King is a gripping psychological thriller that delves into the terrifying consequences of obsession and captivity. The novel follows Paul Sheldon, a bestselling author known for his series of romance novels featuring the beloved character Misery Chastain. After completing his latest manuscript, Paul suffers a car accident in a remote area and is rescued by Annie Wilkes, his self-professed biggest fan." +
                "Annie, a former nurse, cares for Paul in her isolated home, but her initial kindness soon gives way to obsession when she discovers that Paul plans to kill off Misery Chastain in his new novel. Distraught over the impending loss of her favorite character, Annie takes drastic measures to ensure Paul rewrites the novel to resurrect Misery." +
                "What begins as gratitude for saving his life turns into a nightmare as Paul realizes he is a prisoner, entirely at Annie’s mercy. As he struggles to survive physically and mentally, Paul must navigate Annie’s volatile moods and sadistic tendencies while plotting his escape. The claustrophobic atmosphere of Annie’s home intensifies the sense of dread and hopelessness, creating a chilling backdrop for Paul’s desperate bid for freedom." +
                "King’s masterful storytelling explores themes of creativity, addiction, and the blurred boundaries between fiction and reality. Through Paul’s harrowing ordeal, King examines the lengths to which a fan’s devotion can escalate into obsession, blurring the lines between admiration and possession.",
        "book_0031" to "Gone Girl by Gillian Flynn is a dark and twisted psychological thriller that explores the complexities of marriage, deception, and media manipulation. The novel centers around Nick and Amy Dunne, a seemingly perfect couple whose lives unravel on their fifth wedding anniversary when Amy mysteriously disappears. As the search for Amy intensifies, Nick finds himself at the center of a media frenzy and public scrutiny, with suspicions mounting against him." +
                "Flynn expertly navigates between Nick’s present-day perspective and Amy’s diary entries, revealing layers of secrets and unreliable narrators. The novel challenges perceptions as it unravels the facade of a happy marriage, exposing the darker truths hidden beneath. As Nick struggles to prove his innocence while grappling with his own doubts about Amy’s disappearance, Flynn keeps readers on edge with shocking twists and turns." +
                "Through sharp wit and razor-sharp prose, Flynn examines the dynamics of power, control, and the masks people wear to conceal their true selves. Gone Girl is a gripping exploration of how perceptions can be manipulated and how the media can shape public opinion, blurring the lines between truth and fiction." +
                "Flynn’s portrayal of Nick and Amy’s toxic relationship and the psychological games they play with each other makes Gone Girl a compelling and unsettling read. As the narrative builds to a stunning conclusion, Flynn challenges readers to question their assumptions about love, loyalty, and the lengths people will go to in order to protect their secrets.",
        "book_0032" to "The Paris Apartment by Lucy Foley is a gripping mystery thriller that unfolds against the backdrop of the City of Light. The novel follows Jess and her close friend Ben, who discover a long-abandoned apartment in Paris that belonged to a mysterious woman named Catherine de Medici. Intrigued by the secrets hidden within the apartment, Jess becomes obsessed with uncovering the truth about Catherine’s life and disappearance. " +
                "As Jess delves deeper into Catherine’s story, she unravels a web of deceit, betrayal, and dark family secrets that span generations. The novel alternates between Jess’s present-day investigation and Catherine’s life in 1940s Paris, painting a vivid portrait of love, ambition, and the consequences of ambition." +
                "Foley’s evocative prose captures the allure and mystique of Paris, weaving together historical intrigue with a contemporary mystery. The novel explores themes of identity, obsession, and the power of secrets to shape lives across time.",
        "book_0033" to "The Woman In Cabin 10 by Ruth Ware is a tense and atmospheric thriller that unfolds aboard a luxury cruise ship in the Norwegian fjords. The novel follows travel journalist Lo Blacklock, who secures a coveted assignment to cover the maiden voyage of the Aurora Borealis. Excited for the opportunity, Lo boards the ship, but her dream assignment soon turns into a nightmare when she witnesses a woman being thrown overboard from the cabin next to hers." +
                "As Lo tries to unravel the mystery of what happened to the woman, she encounters skepticism from the ship's crew and fellow passengers, who claim that no one was ever registered in the cabin. Determined to uncover the truth, Lo delves deeper into the dark undercurrents of life aboard the Aurora Borealis, where secrets and lies lurk beneath the surface of luxury." +
                "Ware skillfully builds suspense as Lo becomes increasingly paranoid and isolated, unsure of who she can trust as she navigates the claustrophobic confines of the ship. The novel explores themes of identity, perception, and the devastating consequences of past traumas as Lo races against time to uncover the identity of the mysterious woman and prove her own sanity.",
        "book_0034" to "The Family Upstairs by Lisa Jewell is a compelling psychological thriller that delves into dark family secrets, deception, and the haunting legacy of the past. The novel centers around Libby Jones, who on her twenty-fifth birthday inherits a luxurious mansion in London. Excited to uncover her roots, Libby soon learns that she was adopted and that her biological parents and siblings died in mysterious circumstances in the very house she now owns." +
                "As Libby delves into her family’s dark history, she discovers a tangled web of secrets, betrayal, and cult-like devotion that entwines the lives of the former inhabitants of the house. The novel alternates between Libby’s present-day investigation and the past perspectives of Henry and Lucy, a couple caught up in a sinister and manipulative web orchestrated by their charismatic but malevolent benefactor." +
                "Jewell masterfully weaves together multiple narrative threads, gradually revealing the chilling truth behind the tragedy that befell Libby’s family. The novel explores themes of identity, trauma, and the lingering impact of childhood experiences on adult lives." +
                "The Family Upstairs is a gripping and atmospheric thriller that keeps readers on edge with its haunting atmosphere and unpredictable twists. Jewell’s skillful characterization and evocative prose create a sense of unease and suspense, drawing readers deeper into the mysteries surrounding the house and its inhabitants.",
        "book_0035" to "What Lies Beyond the Woods by Kate Alice Marshall is a chilling young adult horror novel that explores the boundaries between reality and the supernatural. The story follows Maisie, a teenager who lives in a small town surrounded by dense, ominous woods. Legend has it that those who venture into the woods never return, and strange occurrences haunt the town’s inhabitants." +
                "When Maisie’s best friend disappears into the woods, she embarks on a perilous journey to uncover the truth. As Maisie delves deeper into the mysteries of the woods, she discovers dark secrets buried within her town’s history and a malevolent force that threatens everything she holds dear." +
                "Marshall’s atmospheric prose creates a palpable sense of dread and suspense as Maisie navigates the eerie landscape of the woods. The novel explores themes of fear, resilience, and the power of friendship in the face of adversity." +
                "What Lies Beyond the Woods is a haunting and suspenseful tale that keeps readers on edge with its atmospheric setting and gripping narrative. Marshall’s vivid imagination and knack for crafting tension make this novel a compelling read for fans of supernatural thrillers and horror fiction." +
                "With its compelling protagonist and spine-chilling plot twists, What Lies Beyond the Woods is sure to captivate readers who enjoy stories that blend the supernatural with themes of courage and self-discovery.",
        "book_0036" to "What Lies Beyond the Veil (Of Flesh and Bone, #1) by Harper L. Woods is a dark fantasy novel that plunges readers into a world of magic, mystery, and supernatural intrigue. The story follows Elara Ashen, a young mercenary with a mysterious past and a hidden power. In a realm where magic is both feared and coveted, Elara navigates a dangerous landscape fraught with political intrigue and ancient secrets." +
                "As Elara uncovers the truth about her own abilities and the dark forces at play in her world, she must confront powerful enemies and make alliances with unlikely allies. The novel explores themes of identity, destiny, and the consequences of wielding supernatural powers in a world on the brink of chaos." +
                "Woods' vivid world-building and intricate plot twists create a compelling narrative that blends elements of dark fantasy with elements of mystery and adventure. What Lies Beyond the Veil is a gripping tale that keeps readers on the edge of their seats with its unpredictable plot and morally ambiguous characters." +
                "With its immersive setting and complex protagonist, What Lies Beyond the Veil is sure to appeal to fans of fantasy fiction looking for a fresh take on the genre. Harper L. Woods' debut novel promises an exhilarating journey into a world where magic and danger collide, setting the stage for an epic series filled with intrigue and suspense.",
        "book_0037" to "One by One by Ruth Ware is a gripping psychological thriller that unfolds against the backdrop of a remote ski chalet in the French Alps. The novel follows a group of colleagues from a tech startup who embark on a corporate retreat to strategize and relax. However, tensions rise as a snowstorm traps them in the chalet, isolating them from the outside world." +
                "As the group becomes increasingly paranoid and distrustful of each other, a series of mysterious incidents and accidents begin to occur, leading to suspicion and fear. The tension escalates when it becomes clear that someone among them is a killer, picking them off one by one." +
                "Ware’s skillful narrative alternates between multiple perspectives, delving into the complex dynamics and hidden agendas of each character. The novel explores themes of ambition, betrayal, and the lengths people will go to in order to survive." +
                "With its claustrophobic setting and relentless pacing, One by One keeps readers on edge with its twists and turns. Ware’s evocative prose and keen insight into human psychology make this thriller a compelling and suspenseful read, as the characters’ secrets and vulnerabilities are laid bare in the face of danger.",
        "book_0038" to "Time War: Onslaught by Nick S. Thomas is a thrilling science fiction novel that takes readers on an epic journey through time and space. The story follows a group of elite soldiers known as the Temporal Defence Squadron (TDS), who are tasked with protecting the timeline from rogue factions seeking to alter history for their own gain." +
                "As the TDS battles across different eras and dimensions, they encounter formidable enemies and face moral dilemmas that challenge their beliefs and loyalty. The novel explores themes of sacrifice, duty, and the consequences of wielding power over time itself." +
                "Thomas’ imaginative world-building and intricate plot twists create a gripping narrative that blends action-packed sequences with thought-provoking exploration of temporal paradoxes and alternate realities. Time War: Onslaught is a rollercoaster ride of adrenaline-pumping adventure and philosophical depth, keeping readers engrossed from start to finish." +
                "With its expansive universe and diverse cast of characters, Time War: Onslaught is sure to appeal to fans of science fiction who enjoy complex narratives and high-stakes conflicts. Nick S. Thomas’ novel promises an exhilarating exploration of time travel and its implications, setting the stage for an epic series filled with thrilling twists and turns.",
        "book_0039" to "Red Mars by Kim Stanley Robinson is a classic science fiction novel that explores the colonization and terraforming of Mars. Set in the near future, the story follows the first hundred colonists who arrive on Mars to establish a new society. Each character brings their own ambitions, ideologies, and struggles as they grapple with the challenges of survival and the ethical dilemmas of transforming an alien planet into a habitable environment." +
                "Robinson’s narrative spans generations, exploring the political, social, and environmental implications of Mars colonization. The novel delves into themes of exploration, terraforming technology, and the complexities of human relationships in extreme conditions." +
                "With meticulous attention to scientific detail and rich character development, Red Mars immerses readers in a realistic vision of humanity’s future on the Red Planet. Robinson’s prose combines scientific speculation with philosophical introspection, offering a compelling reflection on the potential and pitfalls of planetary engineering." +
                "Red Mars is the first installment in Robinson’s Mars trilogy, known for its expansive scope and depth of exploration into the human condition. The novel’s blend of hard science fiction and sociopolitical drama has cemented its place as a seminal work in the genre, appealing to readers who enjoy speculative fiction that explores big ideas and the challenges of human expansion beyond Earth.",
        "book_0040" to "The Sirens Of Titan by Kurt Vonnegut is a satirical science fiction novel that explores themes of free will, destiny, and the absurdity of human existence. The story follows Malachi Constant, a wealthy but aimless man who embarks on a journey through space and time after being contacted by Winston Niles Rumfoord, a billionaire with an unconventional plan for humanity’s future." +
                "As Malachi travels across the solar system and beyond, he encounters bizarre and humorous situations, including encounters with alien civilizations and the mysterious chrono-synclastic infundibulum, which distorts reality and time itself. Along the way, Vonnegut uses his trademark wit and irony to critique societal norms, religion, and the human pursuit of meaning in a seemingly indifferent universe." +
                "The Sirens Of Titan is known for its thought-provoking exploration of existential themes and its unconventional narrative structure. Vonnegut’s prose combines philosophical inquiry with sharp social commentary, offering readers a unique blend of humor and profundity." +
                "With its inventive plot and memorable characters, The Sirens Of Titan remains a beloved classic in science fiction literature. Vonnegut’s ability to blend speculative elements with deep philosophical insights has earned the novel a lasting place in the genre, appealing to readers who appreciate fiction that challenges conventions and explores the complexities of human experience.",
        "book_0041" to "Low Chicago is part of the Wild Cards series, edited by George R.R. Martin, and features a collaborative effort by various authors within the shared universe. This installment explores an alternate history where an alien virus has altered the course of human evolution, granting superpowers to some (Aces) while others are mutated (Jokers)." +
                "In Low Chicago, the city of Chicago is reshaped by the influence of these powers, with political intrigue and personal vendettas playing out against a backdrop of supernatural abilities. The narrative weaves together multiple storylines and perspectives, showcasing the diverse experiences of those affected by the virus and its consequences." +
                "The Wild Cards series is renowned for its complex characters and intricate world-building, offering readers a blend of superhero tropes with nuanced explorations of power, identity, and societal dynamics. Low Chicago continues to expand on these themes while introducing new twists and revelations that keep the series fresh and engaging." +
                "With its ensemble cast and interconnected plotlines, Low Chicago invites readers into a gritty and fantastical world where the line between hero and villain is often blurred. Fans of urban fantasy and superhero fiction will find plenty to enjoy in this latest installment of the Wild Cards saga.",
        "book_0042" to "How to Live Safely in a Science Fictional Universe is a unique blend of science fiction and metafiction that follows the life of Charles Yu, a time machine repairman who navigates a universe where time travel is possible but fraught with paradoxes and uncertainties. The novel explores themes of loneliness, identity, and the search for meaning in a universe where reality itself can be fluid and uncertain." +
                "Yu's narrative is filled with wit and introspection as he grapples with his relationship with his father, who invented time travel but is now lost in time. As Yu embarks on a journey to find his father and understand his own existence, he encounters eccentric characters and navigates through layers of time and space, all while reflecting on the nature of storytelling and the construction of reality." +
                "Through its inventive narrative structure and playful exploration of science fiction tropes, How to Live Safely in a Science Fictional Univers challenges readers to question the boundaries between fiction and reality. Yu's prose is both philosophical and humorous, offering a meditation on the human condition and the ways in which we construct narratives to make sense of our lives." +
                "This novel is a compelling read for fans of literary science fiction that pushes the boundaries of genre conventions while offering a deeply introspective look at what it means to exist in a universe where anything is possible.",
        "book_0043" to "Exhalation is a collection of science fiction short stories by Ted Chiang, known for his thought-provoking explorations of philosophical and ethical themes through speculative fiction. The collection includes several award-winning stories, each offering a deep dive into complex ideas and scenarios." +
                "One of the standout stories in Exhalation is The Lifecycle of Software Objects, which explores the ethical implications of creating artificial intelligence and the relationships that develop between humans and their creations over time. Another notable story, The Merchant and the Alchemist's Gate, intertwines themes of time travel with moral dilemmas and the consequences of altering the past." +
                "Chiang's prose is characterized by its clarity and intellectual rigor, often blending scientific concepts with profound philosophical insights. Each story in Exhalation invites readers to contemplate the nature of consciousness, the limits of human knowledge, and the ethical responsibilities that come with technological advancement." +
                "Overall, Exhalation showcases Chiang's mastery of the short story form and his ability to provoke thought and emotion through his narratives. It is a must-read for fans of speculative fiction who enjoy stories that challenge assumptions and explore the complexities of human existence in extraordinary contexts.",
        "book_0044" to "The novel tells the story of Victor Frankenstein, a young scientist who becomes obsessed with the idea of creating life from dead tissue. Through his experiments, he succeeds in bringing a creature to life, but soon realizes the horrifying implications of his actions." +
                "The creature, initially a benevolent being eager to learn about humanity and find companionship, is rejected and mistreated by society due to its grotesque appearance. This rejection leads the creature to seek revenge against its creator, setting off a tragic chain of events that explores the limits of human empathy and the moral responsibilities of scientific discovery." +
                "Shelley's prose is haunting and atmospheric, evoking a sense of dread and moral ambiguity as the narrative unfolds through multiple perspectives. Frankenstein is not only a gripping tale of horror and suspense but also a profound meditation on the ethics of scientific experimentation and the nature of humanity itself." +
                "As one of the earliest works of science fiction, Frankenstein continues to resonate with readers for its exploration of timeless themes and its portrayal of the complexities of human emotions and motivations. It remains a cornerstone of literary and philosophical discourse, challenging readers to consider the ethical implications of technological innovation and the pursuit of knowledge.",
        "book_0045" to "The Pillars of the Earth by Ken Follett is a historical novel set in 12th-century England, revolving around the construction of a cathedral in the fictional town of Kingsbridge. The novel spans several decades and follows the lives of various characters—builders, clergy, nobles, and common folk—whose fates are intertwined with the ambitious project." +
                "At its heart, The Pillars of the Earth is a story of ambition, power struggles, love, and betrayal set against the backdrop of medieval England. Follett meticulously recreates the period's historical detail, from the intricacies of cathedral architecture to the political and social dynamics of the time." +
                "The novel explores themes of faith, resilience, and the pursuit of dreams amidst adversity. Through its diverse cast of characters, Follett paints a vivid picture of medieval life and the challenges faced by those striving to leave a lasting legacy." +
                "The Pillars of the Earth has garnered acclaim for its epic scope, richly developed characters, and immersive storytelling. It has captivated readers with its blend of historical accuracy and compelling drama, making it a beloved classic in historical fiction." +
                "For readers who enjoy sweeping historical sagas filled with intrigue and human drama, The Pillars of the Earth offers a memorable journey through a pivotal period in European history, centered around the monumental task of building a cathedral that stands as a symbol of hope and faith.",
        "book_0046" to "All the Light We Cannot See is a Pulitzer Prize-winning novel by Anthony Doerr, set during World War II and centered around the lives of two protagonists: Marie-Laure, a blind French girl, and Werner, a German orphan recruited by the Nazi army. The novel intricately weaves their stories together against the backdrop of the war-torn Europe." +
                "Marie-Laure's father, a locksmith at the Museum of Natural History in Paris, constructs a miniature model of their neighborhood to help her navigate the world without sight. When Paris falls to the Germans, they flee to the walled citadel of Saint-Malo, where they harbor a precious gem from the museum." +
                "Meanwhile, Werner is selected to attend a brutal Nazi academy, where his technical aptitude earns him a place in the German army's elite. As the war progresses, their paths converge in Saint-Malo, where both face profound moral dilemmas and the devastation of war." +
                "Doerr's prose is lyrical and evocative, capturing the essence of wartime Europe with vivid detail and emotional resonance. The novel explores themes of resilience, humanity, and the transformative power of compassion amid the chaos and brutality of war." +
                "All the Light We Cannot See is celebrated for its poignant storytelling, rich character development, and haunting portrayal of the human spirit's capacity for both darkness and light. It remains a powerful testament to the enduring impact of love and courage in the face of adversity." +
                "For readers who appreciate historical fiction that delves deep into the complexities of human experience, All the Light We Cannot See offers a compelling narrative that lingers in the heart and mind long after the final page is turned.",
        "book_0047" to "The Crimson Thread by Kate Forsyth is a historical fiction novel that weaves together the lives of two women across different centuries. The story unfolds in two parallel narratives: one set in 1854 during the Crimean War, and the other in present-day Australia." +
                "In the 1854 storyline, we follow the journey of Grace, a nurse who becomes entangled in the horrors of war while caring for wounded soldiers in the Crimea. Amidst the chaos, she forms a bond with a mysterious patient whose identity holds surprising connections to her own past." +
                "In the contemporary narrative, we meet Viviane, an Australian journalist who stumbles upon a series of letters from the Crimean War era. As she delves deeper into the letters' secrets, Viviane uncovers a hidden family history that resonates with her own struggles and aspirations." +
                "Forsyth's novel is rich in historical detail and emotional depth, exploring themes of love, resilience, and the enduring impact of war on individuals and families. The dual timeline structure allows for a nuanced exploration of how past events shape present lives and identities." +
                "The Crimson Thread is praised for its intricate storytelling and well-researched historical backdrop, offering readers a captivating blend of romance, mystery, and historical drama. Forsyth's ability to intertwine past and present narratives creates a compelling narrative that draws readers into the lives of its vibrant characters." +
                "For fans of historical fiction that spans generations and continents, The Crimson Thread offers a poignant exploration of love and loss, courage and sacrifice, against the backdrop of significant historical events.",
        "book_0048" to "The Horseman by Tim Pears is a novel set in rural England before and during World War I, focusing on the life of a young boy named Leo Sercombe. The story unfolds in the early 20th century against the backdrop of a changing agricultural landscape and the looming shadow of war." +
                "Leo, a farm boy with a deep connection to the land and horses, forms a bond with a neighboring girl named Lottie, whose family owns a large estate. Their friendship blossoms amidst the challenges of class divisions and societal expectations, offering a poignant exploration of innocence, love, and coming-of-age in a time of great upheaval." +
                "As World War I unfolds, Leo's journey takes him away from his rural roots and into the brutal realities of war. The novel poignantly captures the impact of historical events on individual lives, highlighting themes of loyalty, courage, and the enduring bonds that transcend time and distance." +
                "Pears' prose is lyrical and evocative, painting a vivid portrait of English countryside life and the profound transformations brought about by war. The Horseman is celebrated for its immersive storytelling and its exploration of universal themes through the lens of personal and historical experience." +
                "For readers who appreciate literary fiction that combines historical depth with lyrical prose and nuanced character development, The Horseman offers a compelling and moving narrative that resonates long after the final page is turned",
        "book_0049" to "The Mirror Fractured Path by J.C. Cervantes invites readers into a world where ancient myths intertwine with modern-day struggles, blending the allure of magic with the complexities of human emotions. The story unfolds through the eyes of a young protagonist, whose ordinary life is abruptly transformed when they discover a hidden realm beyond the ordinary veil of reality." +
                "Set against a backdrop of mystical landscapes and mythical creatures, the novel follows the protagonist's journey of self-discovery and courage. As they navigate through unfamiliar terrains and encounter allies and adversaries alike, they uncover long-lost secrets that hold the key to their own identity and the fate of both worlds." +
                "Cervantes' narrative prowess shines through vivid descriptions and intricate world-building, immersing readers in a tapestry of cultures and folklore. From bustling marketplaces bustling with magical beings to ancient ruins shrouded in mystery, each setting breathes life into the story, enriching the reader's experience with every turn of the page." +
                "At its core, The Mirror Fractured Path explores universal themes of friendship, resilience, and the timeless battle between light and darkness. The protagonist's growth is mirrored by their relationships with a diverse cast of characters, each with their own motivations and burdens to bear." +
                "With prose that is both lyrical and accessible, Cervantes crafts a narrative that resonates on multiple levels, offering readers a journey that is as much about inner strength as it is about outer challenges. Through moments of triumph and heartache, the novel invites reflection on the power of choice and the consequences of wielding magic in a world where every decision carries weight.",
        "book_0050" to "Voices of the Dead by Peter Leonard is a crime thriller that immerses readers in the gritty underworld of Detroit. The novel follows the story of a former journalist turned private investigator, who becomes embroiled in a complex murder case with far-reaching implications." +
                "Set against the backdrop of Detroit's urban decay and political corruption, the protagonist navigates a web of deceit and danger as they uncover shocking truths about the victim and the powerful forces determined to bury them." +
                "Leonard's narrative unfolds with gritty realism and sharp dialogue, capturing the pulse of a city plagued by crime and despair. The protagonist's quest for justice is driven by a personal vendetta and a desire to uncover the truth, even as they confront their own demons and vulnerabilities along the way." +
                "As the investigation deepens, Voices of the Dead delves into themes of betrayal, redemption, and the blurred lines between right and wrong. The novel's multi-layered plot twists and turns, keeping readers on edge and questioning the motives of every character involved." +
                "Through Leonard's skilled prose and atmospheric storytelling, Voices of the Dead offers a thrilling ride through the underbelly of Detroit, where danger lurks around every corner and trust is a rare commodity. The novel's exploration of moral ambiguity and the consequences of unchecked power adds depth to its fast-paced narrative, making it a compelling read for fans of crime fiction and suspense.",
        "book_0051" to "The Winter Palace by Paul Morgan is a historical fiction novel that transports readers to the opulent world of Imperial Russia during the reign of Catherine the Great. The novel unfolds through the eyes of a young woman who rises from obscurity to become a powerful figure in the Russian court." +
                "Against the backdrop of lavish palaces, political intrigue, and the tumultuous events of the 18th century, the protagonist navigates a treacherous path to secure her place among the elite. Her journey is fraught with betrayal, romance, and alliances that shape the course of Russian history." +
                "Morgan's prose is rich with detail and historical accuracy, capturing the grandeur and decadence of the Russian aristocracy. From the majestic halls of the Winter Palace to the icy landscapes of St. Petersburg, the novel immerses readers in a world of splendor and ambition." +
                "The Winter Palace is praised for its meticulous research and compelling portrayal of Catherine the Great's era, offering readers a glimpse into the inner workings of one of history's most intriguing periods. The novel's blend of political drama and personal intrigue creates a captivating narrative that unfolds against the backdrop of a changing empire.",
        "book_0052" to "If Something Happens to Me by Alex Finlay is a suspenseful thriller that unravels a web of secrets and lies surrounding a mysterious death. The novel follows the aftermath of a shocking murder in a small town, where dark secrets begin to surface among the residents." +
                "As the investigation unfolds, the protagonist—a determined detective—uncovers a series of interconnected betrayals and hidden motives that lead to unexpected revelations about the victim and the community at large. Tensions escalate as old grudges resurface and alliances are tested, revealing the true nature of relationships and the lengths people will go to protect their secrets." +
                "Finlay's narrative is gripping and atmospheric, drawing readers into a tightly woven plot filled with twists and turns. The novel delves into themes of trust, deception, and the consequences of past actions, keeping readers guessing until the final, shocking reveal." +
                "Through its vivid characterization and suspenseful pacing, If Something Happens to Me explores the darker side of human nature and the fragile boundaries between innocence and guilt. The protagonist's relentless pursuit of justice adds a layer of urgency to the narrative, driving the story forward with relentless momentum.",
        "book_0053" to "The Family Experiment by John Marrs is a gripping psychological thriller that explores the consequences of a groundbreaking genetic experiment. In a near-future world where scientific advancements have blurred the lines between ethics and innovation, the novel follows a family at the center of a controversial genetic trial." +
                "As the family grapples with the implications of their participation in the experiment, they are thrust into a web of secrecy, manipulation, and unforeseen consequences. The protagonist, a parent torn between hope and fear, must navigate treacherous terrain to protect their loved ones while confronting moral dilemmas that challenge their beliefs and values." +
                "Marrs' narrative unfolds with suspenseful pacing and intricate plot twists, delving into themes of identity, responsibility, and the pursuit of scientific progress at any cost. The novel's exploration of genetic engineering raises thought-provoking questions about the boundaries of scientific ethics and the potential impacts on future generations." +
                "Through its compelling characters and thought-provoking premise, The Family Experiment offers a riveting exploration of human resilience and the lengths people will go to safeguard their loved ones. Marrs' blend of psychological tension and ethical quandaries makes this novel a captivating read for fans of suspense and speculative fiction alike.",
        "book_0054" to "Every Move You Make by C.L. Taylor is a psychological thriller that delves into the dangers of online stalking and obsession. The novel follows the story of a protagonist who becomes the target of a relentless cyber-stalker, whose motives and identity remain shrouded in mystery." +
                "As the protagonist's life unravels under the constant surveillance and harassment, they must unravel the truth behind their stalker's intentions before it's too late. Taylor's narrative unfolds with escalating tension and twists, exploring themes of trust, paranoia, and the blurred boundaries between virtual and real-life threats." +
                "Through its gripping plot and chilling portrayal of modern-day dangers, Every Move You Make captures the pervasive fear of being watched and pursued in the digital age. The novel's exploration of the protagonist's vulnerability and resilience offers a compelling examination of the psychological toll of cyber-stalking." +
                "For readers who enjoy suspenseful narratives that delve into the complexities of human behavior and the dark side of technology, Every Move You Make delivers a riveting and thought-provoking story that keeps readers on edge until the final, shocking conclusion.",
        "book_0055" to "The Wrong Sister by Claire Douglas is a gripping psychological thriller that explores the complexities of sisterhood and deception. The novel centers around the lives of two sisters, whose bond is tested when one of them goes missing under suspicious circumstances." +
                "As secrets from the past resurface and suspicions mount, the protagonist—a determined sibling—uncovers a web of lies and betrayals that lead to shocking revelations about both sisters' lives. Douglas' narrative unfolds with suspenseful pacing and unexpected twists, exploring themes of identity, guilt, and the consequences of buried secrets." +
                "Through its skillful characterization and atmospheric storytelling, The Wrong Sister delves into the intricacies of family dynamics and the blurred lines between truth and fiction. The novel's exploration of unreliable narrators and shifting perspectives adds layers of intrigue to its suspenseful plot, keeping readers guessing until the final, dramatic reveal." +
                "For fans of psychological suspense and intricate mysteries, The Wrong Sister offers a compelling blend of gripping storytelling and nuanced character development. It's a thrilling exploration of the bonds that bind us and the dark secrets that threaten to tear us apart.",
        "book_0056" to "A Lesson in Cruelty by Harriet Tyce is a dark and intense psychological thriller that delves into the complexities of power, desire, and obsession. The novel follows the story of a protagonist who becomes entangled in a dangerous game of manipulation and revenge." +
                "As the protagonist's life spirals out of control, they are drawn into a web of deceit and betrayal that threatens to destroy everything they hold dear. Tyce's narrative unfolds with gritty realism and emotional intensity, exploring themes of ambition, morality, and the consequences of crossing moral boundaries." +
                "Through its compelling characters and suspenseful plot twists, A Lesson in Cruelty challenges readers to confront uncomfortable truths about human nature and the lengths people will go to achieve their desires. The novel's exploration of psychological trauma and the complexities of relationships adds depth to its chilling portrayal of obsession and control." +
                "For readers who enjoy dark and thought-provoking thrillers that delve into the darker aspects of the human psyche, A Lesson in Cruelty offers a compelling and unsettling journey into the depths of human obsession and the consequences of unchecked ambition.",
        "book_0057" to "The Trial by Jo Spain is a gripping courtroom drama that unravels the complexities of justice, truth, and moral ambiguity. The novel follows the trial of a high-profile case that captivates the nation, where the lines between guilt and innocence blur amidst intense media scrutiny and public opinion." +
                "As the courtroom drama unfolds, Spain's narrative dives into the lives of the accused, the victims, and those caught in the crossfire of a legal battle that exposes hidden truths and challenges societal norms. The protagonist—a dedicated lawyer—must navigate through a maze of conflicting evidence and personal agendas to uncover the real story behind the crime." +
                "Through its intricate plot and compelling character development, the Trial explores themes of privilege, prejudice, and the pursuit of justice in a modern society gripped by sensationalism and media frenzy. Spain's exploration of legal ethics and the complexities of human nature adds depth to the novel's exploration of morality and truth."
    )

    private val authors = mapOf(
        "book_0001" to "Casey McQuiston",
        "book_0002" to "Charlotte Brontë",
        "book_0003" to "E L James",
        "book_0004" to "Rainbow Rowell",
        "book_0005" to "Jasmine Guillory",
        "book_0006" to "Erica Lee",
        "book_0007" to "Jennifer Wilck",
        "book_0008" to "Erica Lee",
        "book_0009" to "Clare Whitfield",
        "book_0010" to "Kater Cheek",
        "book_0011" to "Gregg Olsen",
        "book_0012" to "Patrick Modiano",
        "book_0013" to "Libby Page",
        "book_0014" to "Walt Disney",
        "book_0015" to "M.B. Henry",
        "book_0016" to "Makoto Shinkai",
        "book_0017" to "Author 10",
        "book_0018" to "Sou Hazuki",
        "book_0019" to "Shirotaka",
        "book_0020" to "Gege Akutami",
        "book_0021" to "Hajime Isayama",
        "book_0022" to "Masashi Kishimoto",
        "book_0023" to "Candace Fox",
        "book_0024" to "Agatha Christie",
        "book_0025" to "Agatha Christie",
        "book_0026" to "Oscar Wilde",
        "book_0027" to "Laura Wolfe",
        "book_0028" to "John Manning",
        "book_0029" to "Agatha Christie",
        "book_0030" to "Stephen King",
        "book_0031" to "",
        "book_0032" to "Lucy Foley",
        "book_0033" to "Ruth Ware",
        "book_0034" to "Lisa Jewell",
        "book_0035" to "Kate Alice Marshall",
        "book_0036" to "Harper L. Woods",
        "book_0037" to "Ruth Ware",
        "book_0038" to "Nick S. Thomas",
        "book_0039" to "Kim Stanley Robinson",
        "book_0040" to "Kurt Vonnegut",
        "book_0041" to "Wild Cards Trust",
        "book_0042" to "Charles Yu",
        "book_0043" to "Ted Chiang",
        "book_0044" to "Mary Shelley",
        "book_0045" to "Ken Follett",
        "book_0046" to "Anthony Doerr",
        "book_0047" to "Kate Forsyth",
        "book_0048" to "Tim Pears",
        "book_0049" to "J.C. Cervantes",
        "book_0050" to "Peter Leonard",
        "book_0051" to "Paul Morgan",
        "book_0052" to "Alex Finlay",
        "book_0053" to "John Marrs",
        "book_0054" to "C.L. Taylor",
        "book_0055" to "Claire Douglas",
        "book_0056" to "Harriet Tyce",
        "book_0057" to "Jo Spain"
    )

    private val namae = mapOf(
        "book_0001" to "Red, White & Royal Blue",
        "book_0002" to "Jane Eyre (Minimalist Classics)",
        "book_0003" to "Fifty Shades of Grey",
        "book_0004" to "Eleanor and Park",
        "book_0005" to "The Proposal",
        "book_0006" to "And Then I Met You",
        "book_0007" to "A Reckless Heart",
        "book_0008" to "The Finish Line",
        "book_0009" to "People of Abandoned Character",
        "book_0010" to "Library of Abandoned Angels",
        "book_0011" to "If You Tell",
        "book_0012" to "Invisible Ink",
        "book_0013" to "The Lido",
        "book_0014" to "The Art of Walt Disney",
        "book_0015" to "All the Lights Above Us",
        "book_0016" to "Suzume no Tojimari",
        "book_0017" to "Author 10",
        "book_0018" to "Weather Girl",
        "book_0019" to "Farming Life in Another World",
        "book_0020" to "Jujutsu Kaisen",
        "book_0021" to "Attack on Titan",
        "book_0022" to "Naruto",
        "book_0023" to "Gathering Darkness",
        "book_0024" to "Murder on the Orient Express",
        "book_0025" to "Death on the Nile",
        "book_0026" to "The Picture of Dorian Gray",
        "book_0027" to "The Forgotten Orphan",
        "book_0028" to "All the Pretty Horses",
        "book_0029" to "The Murder of Roger Ackroyd",
        "book_0030" to "The Shining",
        "book_0031" to "Untitled Book",
        "book_0032" to "The Hunting Party",
        "book_0033" to "The Woman in Cabin 10",
        "book_0034" to "Then She Was Gone",
        "book_0035" to "I Am Still Alive",
        "book_0036" to "Cursed Hearts",
        "book_0037" to "In a Dark, Dark Wood",
        "book_0038" to "The Young Lions",
        "book_0039" to "Red Mars",
        "book_0040" to "Slaughterhouse-Five",
        "book_0041" to "Wild Cards",
        "book_0042" to "Interior Chinatown",
        "book_0043" to "Stories of Your Life and Others",
        "book_0044" to "Frankenstein",
        "book_0045" to "The Pillars of the Earth",
        "book_0046" to "All the Light We Cannot See",
        "book_0047" to "Bitter Greens",
        "book_0048" to "In the Light of Morning",
        "book_0049" to "The Storm Runner",
        "book_0050" to "Voices",
        "book_0051" to "Lions of the West",
        "book_0052" to "The Night Shift",
        "book_0053" to "The Passengers",
        "book_0054" to "Sleep",
        "book_0055" to "Just Like the Other Girls",
        "book_0056" to "Blood Orange",
        "book_0057" to "The Confession"

    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_book_info)

        val pdfName = intent.getStringExtra("pdfName") ?: return
        val bookImageView = findViewById<ImageView>(R.id.bookImageView)
        val bookDescription = findViewById<TextView>(R.id.bookDescriptionTextView)
        val bookTitle = findViewById<TextView>(R.id.bookTitleTextView)
        val bookAuthor = findViewById<TextView>(R.id.bookAuthorTextView)
        val readButton = findViewById<Button>(R.id.readButton)

        val bookImageResId = resources.getIdentifier(pdfName, "drawable", packageName)
        bookImageView.setImageResource(bookImageResId)
        bookTitle.text = namae[pdfName]
        bookAuthor.text = authors[pdfName]
        bookDescription.text = descriptions[pdfName]

        readButton.setOnClickListener {
            val intent = Intent(this, PdfViewerActivity::class.java)
            intent.putExtra("pdfName", pdfName)
            startActivity(intent)
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            window.navigationBarColor = resources.getColor(R.color.lightRed, theme)
        }
    }
}
